/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Evi
 */
public class enkripsi extends javax.swing.JFrame {
    
    private static final int m = 26;
    private final int[][] M = new int[2][2];

    private final int p[] = new int[100];
    private final int c[] = new int[100];
    char[] f = new char[100];
    /**
     * Creates new form
     */
    public enkripsi() {
        initComponents();
        
        kontrolTbl();
    }
    
     private static int tambah(int a, int b) {
        return (a - b) ;
     }
 private static boolean adaInvers( int tambah) {
    boolean hasil = false;
    if ((tambah) == 0) {
        hasil = false;
    } else {
        hasil = true;     
    }
    return hasil;
 }
 public void GetM() {
    M[0][0] = Integer.parseInt(tf1.getText());
    M[0][1] = Integer.parseInt(tf2.getText());
    M[1][0] = Integer.parseInt(tf3.getText());
    M[1][1] = Integer.parseInt(tf4.getText());
 }

public int[][] setKunci() {
    int K[][] = {
    {Integer.parseInt(tf1.getText()),
   Integer.parseInt(tf2.getText())},
    {Integer.parseInt(tf3.getText()),
   Integer.parseInt(tf4.getText())}
    };
    return this.M;
}
 
 private static boolean CekDeterminan(int[][] M) {
    int x = (M[0][0] * M[1][1]) ;
    int y = (M[1][0] * M[0][1]) ;
    int z = tambah(x, y);
    return adaInvers(z);
 }
 public void kontrolTbl() {
    btnenkripsi3.setEnabled(false);
    txtcipher1.setEnabled(false);
    txtplain.setEnabled(false);
 }
 public void enablebtn() {
    btnenkripsi3.setEnabled(true);
    txtcipher1.setEnabled(true);
    txtplain.setEnabled(true);
 }
 private int[] enkrip(int[][] M, int[] p) {
    String str = txtcipher1.getText(); // mengambil nilai string
    int i = 0;
    int zz = 0;
    
    for (int b = 0; b < str.length() ; b++) {
       for (int j = 0; j < 2; j++) {
           for (int x = 0; x < 2; x++) {
               c[i] += M[j][x] * p[x + zz]; 
    // mengalikan kunci dengan nilai konversi huruf ke angka
           }
           i++;
       }
       zz += 2;
    }
    return c;
 }
 
 public int[] setP() {
    String str = txtcipher1.getText();
    for (int i = 0; i < str.length(); i++) {
        int c1 = str.charAt(i);
        p[i] = (c1)-97;
       // Mengisi array p dengan konversi String menjadi bilangan integer
       //untuk huruf kecil menggunakan angka 97
    }
    return p;
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnenkripsi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtplain = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcipher = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtkunci = new javax.swing.JTextField();
        btnenkripsi2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcipher2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcipher1 = new javax.swing.JTextArea();
        btnenkripsi3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelcek = new javax.swing.JLabel();
        btnkeluar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnenkripsi.setText("Enkripsi ke Caesar Cipher");
        btnenkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenkripsiActionPerformed(evt);
            }
        });
        jPanel1.add(btnenkripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel1.setText("Ciphertext - Hill");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 164, -1, -1));

        jLabel2.setText("Ciphertext - Caesar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        txtplain.setColumns(20);
        txtplain.setRows(5);
        jScrollPane1.setViewportView(txtplain);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 184, -1, 88));

        txtcipher.setColumns(20);
        txtcipher.setRows(5);
        jScrollPane2.setViewportView(txtcipher);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 322, 183, 79));

        jLabel3.setText("Kata kunci");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));
        jPanel1.add(txtkunci, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 191, -1));

        btnenkripsi2.setText("Enkripsi ke Atbash Cipher");
        btnenkripsi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenkripsi2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnenkripsi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        txtcipher2.setColumns(20);
        txtcipher2.setRows(5);
        jScrollPane3.setViewportView(txtcipher2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 437, 183, 78));

        jLabel4.setText("Ciphertext - Atbash");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jLabel5.setText("It's done. From Hill to Caesar to Atbash.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jLabel6.setText("Plaintext");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 11, -1, -1));

        txtcipher1.setColumns(20);
        txtcipher1.setRows(5);
        jScrollPane4.setViewportView(txtcipher1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 32, 160, -1));

        btnenkripsi3.setText("Enkripsi ke Hill Cipher");
        btnenkripsi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenkripsi3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnenkripsi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel7.setText("Kata Kunci");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 11, -1, -1));

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 36, 37, -1));
        jPanel1.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 36, 37, -1));

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        jPanel1.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 66, 37, -1));
        jPanel1.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 66, 37, -1));

        jButton1.setText("cek kunci");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        labelcek.setAutoscrolls(true);
        jPanel1.add(labelcek, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 140, 40));

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PERHATIAN");

        jLabel9.setText("1. Masukkan plaintext menggunakan huruf kecil, tidak boleh huruf kapital.");

        jLabel10.setText("2. Hanya boleh klik button enkripsi 1x. Jika plaintext/ kata kunci salah maka ulangi lagi dari awal.");

        jLabel11.setText("3. Plaintext yang dimasukkan harus genap jumlahnya, jika jumlahnya ganjil maka tambahkan karakter hanya dengan huruf 'z'");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenkripsiActionPerformed
        int key = Integer.parseInt(txtkunci.getText());
        String isitext = txtplain.getText();
        String out = "";
        
        for(int i = 0; i< isitext.length(); i++){
                int index = (isitext.charAt(i)-'a' ) ;
                char s = (char)(((index + key)%26) + 'a');
                out = out+ String.valueOf(s);
        }
        txtcipher.setText(out);
    }//GEN-LAST:event_btnenkripsiActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnenkripsi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenkripsi2ActionPerformed
        String isitext2 = txtcipher.getText(); //plain
        String out ="";

        int m = 26, x;
        char chr2;
        
        for(int i = 0; i< isitext2.length(); i++){
                x = (isitext2.charAt(i)-'a');
                chr2 = (char) (((m-1) * (x+1) % 26) + 'a');
                out = out+chr2;
        }
        txtcipher2.setText(out);
    }//GEN-LAST:event_btnenkripsi2ActionPerformed

    private void btnenkripsi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenkripsi3ActionPerformed
        String str = txtcipher1.getText();
        String out = "";
        setP();
        enkrip(M, p);
        for (int z = 0; z < str.length(); z++) {
            f[z] = (char) ((c[z] % 26) + 97 );//untuk huruf kecil menggunakn angka 97
            out = new String(f).trim();
        }             
        txtplain.setText(out); 
    }//GEN-LAST:event_btnenkripsi3ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        GetM();
        if (CekDeterminan(M)) {
            labelcek.setText("Matriks memiliki invers");
        } else {
            labelcek.setText("Matriks tidak memiliki invers");
        }
        if (CekDeterminan(M)) {
            enablebtn();
        } else {
            kontrolTbl();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenkripsi;
    private javax.swing.JButton btnenkripsi2;
    private javax.swing.JButton btnenkripsi3;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelcek;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextArea txtcipher;
    private javax.swing.JTextArea txtcipher1;
    private javax.swing.JTextArea txtcipher2;
    private javax.swing.JTextField txtkunci;
    private javax.swing.JTextArea txtplain;
    // End of variables declaration//GEN-END:variables
}
